name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  strategy:
    matrix:
      node: ['10', '12']
      os: [ubuntu-latest]

  runs-on: ${{ matrix.os }}

  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: npm install -g yarn

    - id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ matrix.os }}-yarn-

    - run: yarn
    - run: yarn prettier
    - run: yarn build
